#!/usr/bin/env bash

# Set up autograder files

cp -rn /autograder/submission/* /autograder/source/

cd /autograder/source

npx jest --testResultsProcessor jest-autograding-reporter
cp /autograder/source/results.json /autograder/results/results.json